#!/usr/bin/env bash
# Install (or refresh) the Gallery's tiling layer: yabai + skhd, configured from this
# repo. Run from a shell with access to this checkout (Terminal/Claude), on each
# machine that should tile. Idempotent: re-run after editing tiler/yabairc or
# tiler/skhdrc to push the new files and reload both services. Also runs, in order,
# as the first step of the Gallery's own install.sh (unless --skip-tiler).
#
# The rc files are COPIED, not symlinked: launchd starts yabai/skhd, and under
# launchd macOS TCC denies reading the external volume this repo lives on --
# a symlink would just resolve back through that volume and fail the same way.
#
# No scripting addition is installed (no sudoers entry, no `yabai --load-sa`). SIP
# stays enabled; Space switching remains the Mission Control Ctrl+N shortcuts.
#
# A yabai restart rebuilds every BSP tree from scratch (manual split ratios, swaps,
# zoom all lost), so an actual restart is bracketed with tiler/yabai-layout
# save/restore (installed next to yabairc, also for standalone use).
#
#   tiler/install.sh            install/refresh; restart a service only if its
#                               effective config changed (see "services")
#   tiler/install.sh --restart  restart both services even if unchanged
#   tiler/install.sh --dry-run  print what would happen
#   tiler/install.sh --uninstall  stop and unregister both services (and stop
#                                 borders unless it is a brew service), remove
#                                 what this installer wrote and put back any
#                                 file of yours it replaced (keeps the Homebrew
#                                 formulas)
#
# Files of yours are never lost: an existing yabairc, skhdrc or helper that is
# not a Gallery file is moved to <name>.gallery-bak before the new one is
# installed, and --uninstall moves it back. A Gallery file you edited is copied
# to <name>.gallery-edited.<timestamp> before it is overwritten. Everything
# written is listed in ~/.config/gallery/state/install-manifest.tsv (see
# tools/install-lib.sh, which this script sources).
set -euo pipefail
cd "$(dirname "$0")"

DRY=0; UNINSTALL=0; RESTART=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY=1 ;;
        --uninstall) UNINSTALL=1 ;;
        --restart) RESTART=1 ;;
        *) echo "usage: $0 [--dry-run] [--restart] [--uninstall]" >&2; exit 2 ;;
    esac
done

run() { if [ "$DRY" = 1 ]; then echo "[dry] $*"; else echo "[tiler] $*"; "$@"; fi; }

# Backup/manifest helpers shared with the Gallery's install.sh.
if [ ! -f ../tools/install-lib.sh ]; then
    echo "[tiler] ../tools/install-lib.sh is missing -- run this from a complete checkout" >&2; exit 1
fi
GL_DRY="$DRY"; GL_TAG="[tiler]"
# shellcheck source=../tools/install-lib.sh
. ../tools/install-lib.sh

YABAI_RC="$HOME/.config/yabai/yabairc"
SKHD_RC="$HOME/.config/skhd/skhdrc"
YABAI_DIR="$(dirname "$YABAI_RC")"
SKHD_DIR="$(dirname "$SKHD_RC")"

if [ "$UNINSTALL" = 1 ]; then
    # Unregister the launchd services as well as stopping them: their plists
    # are RunAtLoad/KeepAlive, so a stopped-but-registered service would start
    # again at the next login with no rc file to read.
    for f in yabai skhd; do
        if command -v "$f" >/dev/null; then
            run "$f" --stop-service || true
            run "$f" --uninstall-service || true
        fi
    done
    # JankyBorders is started from yabairc, outside launchd. Leave it alone if
    # the user runs it as a brew service of their own.
    if pgrep -xq borders; then
        if command -v brew >/dev/null && brew services list 2>/dev/null | awk '$1 == "borders" && $2 != "none" { found = 1 } END { exit !found }'; then
            echo "[tiler] borders is registered as a brew service; leaving it running"
            gl_note kept "borders (a brew service of yours)"
        else
            run killall borders || true
            gl_note removed "the running borders process"
        fi
    fi
    for f in "$YABAI_RC" "$SKHD_RC" "$SKHD_DIR/tiler.skhd" "$SKHD_DIR/gallery.skhd" "$SKHD_DIR/learn" "$SKHD_DIR/learn.style.json"              "$SKHD_DIR/focus-dir" "$SKHD_DIR/browser-window" "$YABAI_DIR/yabai-layout" "$YABAI_DIR/tree-guard"; do
        gl_uninstall_file "$f"
    done
    # Generated by `learn install`, not copied: a copy next to learn, and the app.
    if [ -e "$SKHD_DIR/Tiler-Keys.md" ]; then
        run rm -f "$SKHD_DIR/Tiler-Keys.md"; gl_note removed "$SKHD_DIR/Tiler-Keys.md"
    fi
    if [ -f "$HOME/Applications/Learn.app/Contents/Info.plist" ] && grep -q org.ottosson.learn "$HOME/Applications/Learn.app/Contents/Info.plist"; then
        run rm -rf "$HOME/Applications/Learn.app"; gl_note removed "$HOME/Applications/Learn.app"
    fi
    gl_rmdir_empty "$HOME/Applications" "$YABAI_DIR" "$SKHD_DIR"
    echo "[tiler] services stopped and unregistered, installed files removed, your own files restored"
    echo "        (no restart needed). Note for external consumers: tools that place windows"
    echo "        should detect yabai's absence at runtime and fall back to System Events placement."
    gl_summary
    exit 0
fi

# --- prerequisites --------------------------------------------------------------
if ! command -v brew >/dev/null; then
    echo "Homebrew is required (https://brew.sh)" >&2; exit 1
fi
# yabai needs each display to have its own Spaces and a stable Space order.
spans="$(defaults read com.apple.spaces spans-displays 2>/dev/null || echo 0)"
mru="$(defaults read com.apple.dock mru-spaces 2>/dev/null || echo 0)"
if [ "$spans" != 0 ]; then
    echo "[tiler] WARNING: 'Displays have separate Spaces' is OFF (System Settings >"
    echo "        Desktop & Dock > Mission Control). yabai needs it ON; log out/in after."
fi
if [ "$mru" != 0 ]; then
    echo "[tiler] WARNING: 'Automatically rearrange Spaces based on most recent use'"
    echo "        is ON. Turn it OFF or Space numbers will drift under you."
fi
if pgrep -xq Magnet || pgrep -xq Rectangle; then
    echo "[tiler] WARNING: another window manager (Magnet/Rectangle) is running; quit it."
fi

# --- install ----------------------------------------------------------------------
for f in yabai skhd; do
    if brew list --formula "$f" >/dev/null 2>&1; then
        echo "[tiler] $f already installed ($(brew list --versions "$f"))"
    else
        run brew install "asmvik/formulae/$f"
    fi
done
# JankyBorders (borders): draws the accent outline around the focused window
# (launched from yabairc). Needs no scripting addition, so SIP stays enabled.
if brew list --formula borders >/dev/null 2>&1; then
    echo "[tiler] borders already installed ($(brew list --versions borders))"
else
    run brew install "FelixKratz/formulae/borders"
fi
# The Learn menu (tiler/learn): fzf picks a sheet, glow renders it.
for f in fzf glow; do
    if brew list --formula "$f" >/dev/null 2>&1; then
        echo "[tiler] $f already installed ($(brew list --versions "$f"))"
    else
        run brew install "$f"
    fi
done

# --- configuration -------------------------------------------------------------------
# The rc files minus comments and blank lines: what a service actually acts on.
# Captured before the copy so the services step can tell a real change from a
# comment-only edit.
effective() { grep -vE '^[[:space:]]*(#|$)' "$1" 2>/dev/null || true; }
yabai_before="$(effective "$YABAI_RC")"
skhd_before="$(effective "$SKHD_RC")$(effective "$SKHD_DIR/tiler.skhd")"

# yabai and skhd read ~/.config/yabai/yabairc and ~/.config/skhd/skhdrc in
# preference to ~/.yabairc and ~/.skhdrc, so a dotfile in $HOME stops being read
# once ours is in place. It is left untouched; say so.
for f in "$HOME/.yabairc:yabai" "$HOME/.skhdrc:skhd"; do
    if [ -f "${f%%:*}" ]; then
        echo "[tiler] WARNING: ${f%%:*} exists. ${f##*:} reads its ~/.config copy first, so that file is now ignored"
        echo "        (it is not modified). Merge what you need into the Gallery's rc, or move it back by"
        echo "        uninstalling."
    fi
done

run install -d "$YABAI_DIR" "$SKHD_DIR"
gl_install_file yabairc "$YABAI_RC" 755
gl_install_file skhdrc  "$SKHD_RC" 644
gl_install_file tiler.skhd "$SKHD_DIR/tiler.skhd" 644
# skhdrc includes gallery.skhd (The Gallery key bindings, same repo now). The
# Gallery installer's own "skhd bindings" step copies the real file in right
# after this one runs; an empty placeholder is written here too so the include
# still resolves -- and a standalone `tiler/install.sh` run (Gallery skipped
# or not yet installed) works on its own.
[ -e "$SKHD_DIR/gallery.skhd" ] || gl_install_file /dev/null "$SKHD_DIR/gallery.skhd" 644
# local.skhd: the user's own key bindings (skhdrc loads it before tiler.skhd and
# gallery.skhd, so it can replace any shipped key).
# Seeded once from the all-commented example so skhd hotloads it from the start;
# NEVER overwritten.
[ -e "$SKHD_DIR/local.skhd" ] || run install -m 644 local.skhd.example "$SKHD_DIR/local.skhd"
# The Learn script lives next to skhdrc (skhd and Learn.app run under launchd, which
# cannot read this volume); it also writes the generated key sheet into the vault
# and builds ~/Applications/Learn.app for Spotlight.
gl_install_file learn "$SKHD_DIR/learn" 755
# focus-dir: the directional focus/swap picker skhdrc calls for super+h/j/k/l.
gl_install_file focus-dir "$SKHD_DIR/focus-dir" 755
# browser-window: super+b's new window in the default browser.
gl_install_file browser-window "$SKHD_DIR/browser-window" 755
gl_install_file learn.style.json "$SKHD_DIR/learn.style.json" 644 1
if [ "$DRY" = 1 ]; then echo "[dry] learn install skhdrc"; else "$SKHD_DIR/learn" install "$PWD/skhdrc"; fi
# yabai-layout: installed next to yabairc (same TCC reasoning) so the save/restore
# wrapper below — and standalone use outside this repo — always run the installed
# copy, never the checkout on the external volume.
gl_install_file yabai-layout "$YABAI_DIR/yabai-layout" 755
gl_install_file tree-guard "$YABAI_DIR/tree-guard" 755

# --- services --------------------------------------------------------------------------
# A running service is restarted so a changed rc file takes effect
# (--start-service on a running service returns 0 without reloading anything).
# Restarting yabai is NOT free: it rebuilds every window tree from scratch, so
# manual split ratios, swaps and zoom state on every display are lost. A
# service is therefore restarted only when its effective config (comments and
# blank lines stripped) differs from what was live before the copy, or with
# --restart. Comment-only edits are copied without touching the services.
for f in yabai skhd; do
    case "$f" in
        yabai) before="$yabai_before"; after="$(effective yabairc)" ;;
        skhd)  before="$skhd_before";  after="$(effective skhdrc)$(effective tiler.skhd)" ;;
    esac
    if [ "$DRY" = 1 ]; then echo "[dry] $f --restart-service if config changed (or --start-service)"; continue; fi
    if ! pgrep -xq "$f"; then
        "$f" --start-service && echo "[tiler] $f service started"
    elif [ "$RESTART" = 1 ] || [ "$before" != "$after" ]; then
        if [ "$f" = "yabai" ]; then
            # A restart wipes the live BSP tree (see header): snapshot it first,
            # restart, then replay it back through the installed yabai-layout.
            YL="$(dirname "$YABAI_RC")/yabai-layout"
            "$YL" save
            "$f" --restart-service && echo "[tiler] $f service restarted"
            "$YL" restore --wait 40
        else
            "$f" --restart-service && echo "[tiler] $f service restarted"
        fi
    else
        echo "[tiler] $f config unchanged, not restarting (--restart to force)"
    fi
done

cat <<'MSG'

[tiler] Manual steps (once per machine):
  1. System Settings > Privacy & Security > Accessibility: tick "yabai" and "skhd"
     (both request it on first start). Then run `yabai --restart-service` and
     `skhd --restart-service` — each must restart after the grant.
  2. System Settings > Keyboard > Keyboard Shortcuts... > Mission Control: enable
     "Switch to Desktop N" for every Desktop you use (super+N and super+shift+N
     ride on these Ctrl+N shortcuts).
  3. Secure Keyboard Entry must be OFF in your terminal, or skhd stops seeing keys
     while it is frontmost (iTerm2, Ghostty and kitty have it in their menus).
  4. Try: left Option+h/j/k/l (focus), left Option+2 (Space 2), right Option+2 (@),
     left Option+space (Learn menu; first press: allow "skhd wants to control" your
     terminal), Cmd+space "Learn" (first launch: allow "Learn wants to control" it).
     The prompts name iTerm2 or Ghostty; kitty and WezTerm raise none.
  Verify: `yabai -m query --displays` lists your displays; `skhd --observe` shows keys.
MSG
